#!/usr/bin/env bash

mkdir -p /opt/ktv/shares/infra /opt/ktv/shares/server

mount -t nfs4 -o nfsvers=4.1 $(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone).fs-328570fb.efs.eu-west-1.amazonaws.com:/ /opt/ktv/shares/infra

mount -t nfs4 -o nfsvers=4.1 $(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone).fs-5785709e.efs.eu-west-1.amazonaws.com:/ /opt/ktv/shares/server

chown www-data:www-data -R /opt/ktv/shares