#!/bin/bash

VOLUME=${VOLUME:-/opt/ktv/shares}
ALLOW=${ALLOW:-192.168.0.0/16 172.16.0.0/12}
OWNER=${OWNER:-www-data}
GROUP=${GROUP:-www-data}

chown "${OWNER}:${GROUP}" "${VOLUME}"

[ -f /etc/rsyncd.conf ] || cat <<EOF > /etc/rsyncd.conf
uid = ${OWNER}
gid = ${GROUP}
use chroot = yes
log file = /dev/stdout
reverse lookup = no
[volume]
    hosts allow = *
    read only = false
    path = ${VOLUME}
    comment = docker volume
EOF

