#!/bin/bash

OWNER=${OWNER:-www-data}
GROUP=${GROUP:-www-data}

chown "${OWNER}:${GROUP}" "${VOLUME}"

[ -f /etc/rsyncd.conf ] || cat <<EOF > /etc/rsyncd.conf
uid = ${OWNER}
gid = ${GROUP}
use chroot = yes
log file = /dev/stdout
reverse lookup = no

[server]
    read only = false
    path = /opt/ktv/shares/server

[infra]
    read only = false
    path = /opt/ktv/shares/infra
EOF

exec /usr/bin/rsync --no-detach --daemon --config /etc/rsyncd.conf "$@"
