#!/bin/bash

echo "Waiting elasticsearch up "

sleep 1

until $(curl --output /dev/null --silent --head --fail http://localhost:9200); do
	printf '.'
	sleep 1
done

curl -XPUT localhost:9200/_template/default -d "$(cat ./index_templates/default.json)"

curl -XPUT localhost:9200/_template/items -d "$(cat ./index_templates/items.json)"

sv stop config