version: "2"

services:

  app:
    build: ./server
    image: ktv_app
    container_name: ktv_app
    hostname: app
    mem_limit: 4G
    ports:
      - 80:80
    environment:
      - KTV_ENV=$KTV_ENV

  mysql:
    build: ./mysql
    image: ktv_mysql
    container_name: ktv_mysql
    hostname: mysql
    mem_limit: 4G
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$KTV_MYSQL_ROOT_PASSWORD

volumes:

  mysql:
    driver: local