version: "2"

services:

  app:
    build: ./app
    image: ktv/app
    container_name: ktv_app
    hostname: app
    ports:
      - 80:80
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/php.ini:/etc/php/7.0/fpm/php.ini:ro
    environment:
      - KTV_ENV=$(KTV_ENV)

  mysql:
    image: percona:5.7
    container_name: ktv_mysql
    hostname: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=$(KTV_MYSQL_ROOT_PASSWORD)

volumes:

  mysql:
    driver: local