version: "2"

services:

  app:
    image: kinoulink/ktv_server
    container_name: ktv_app
    hostname: app
    mem_limit: 268435456
    links:
      - mysql:mysql
    volumes:
      - /opt/ktv/shares/app/dev:/var/www:ro
    ports:
      - 80:80
    environment:
      - KTV_ENV=$KTV_ENV
      - KTV_RELEASE=beta

  mysql:
    image: kinoulink/ktv_data
    container_name: ktv_mysql
    hostname: mysql
    mem_limit: 268435456
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$KTV_MYSQL_ROOT_PASSWORD

volumes:

  mysql:
    driver: local