version: '2'

services:

  mongodb:
    image: kinoulink/mongodb
    ports:
    - 27017:27017
    volumes:
    - /data/mongodb:/data/db:rw
    - ${K_ROOT}/infra/stacks/public/mongo:/share:ro
    container_name: mongodb
    restart: always
    networks:
      - common_default

  api:
    build:
      context: ./api
      args:
        K_ENV: ${K_ENV}
    image: kinoulink/api-${K_ENV}
    expose:
      - 80
    volumes:
    - ${K_ROOT}/api:/var/www:rw
    - /data/upload:/var/kinoulink/upload:rw
    container_name: api
    environment:
      VIRTUAL_HOST: api
    restart: always
    networks:
      - common_default

  webapp:
    build:
      context: ./webapp
#      args:
#        NODE_ENV:${K_ENV}
    image: kinoulink/webapp:${K_ENV}-0.1
    expose:
      - 80
    volumes:
      - ${K_ROOT}/webapp/gen/builds/src/${K_ENV}:/var/www:ro
    container_name: webapp
    environment:
      VIRTUAL_HOST: webapp
    restart: always
    networks:
      - common_default

  mongodb_ui:
    image: knickers/mongo-express
    expose:
      - 8081
    container_name: mongodb_ui
    environment:
      VIRTUAL_HOST: mongodb.admin
      ME_CONFIG_MONGODB_SERVER: mongodb
    restart: always
    networks:
      - common_default

  proxy:
    build:
      context: ./proxy
    image: kinoulink/api-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: proxy
    restart: always
    networks:
      - common_default

networks:

  common_default:
    external: true