version: '2'

services:

  mongo:
    image: bizlunch/mongodb
    ports:
    - 27017:27017
    volumes:
    - /data/mongodb:/data/db:rw
    - /var/bizlunch/infra/stacks/public/mongo:/share:ro
    container_name: mongo

  messenger:
    image: bizlunch/messenger
    volumes:
      - /var/bizlunch/chat:/var/www:ro
    expose:
      - 80
    container_name: messenger

  elasticsearch:
    image: bizlunch/search
    ports:
    - 9200:9200
    volumes:
    - /data/elasticsearch:/usr/share/elasticsearch/data:rw
    container_name: elasticsearch

  api:
    image: bizlunch/api
    expose:
      - 80
    volumes:
    - /var/bizlunch/infra/stacks/public/api/nginx:/etc/service/nginx/config:ro
    - /var/bizlunch/infra/stacks/public/api/php-fpm:/etc/service/phpfpm/config:ro
    - /var/bizlunch/api:/var/www:rw
    container_name: api

  webapp:
    image: bizlunch/webapp
    expose:
      - 80
    volumes:
      - /var/bizlunch/infra/stacks/public/webapp/nginx:/etc/service/nginx/config:ro
      - /var/bizlunch/webapp:/var/bizlunch:ro
    container_name: webapp

  proxy:
    image: bizlunch/nginx
    volumes:
      - /var/bizlunch/infra/stacks/public/proxy/nginx:/etc/service/nginx/config:ro
    ports:
      - 80:80
    container_name: proxy