# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.define "kinoulink-public" do |box|
  end

  config.vm.hostname = "local.kinoulink.com"

  config.ssh.username = "vagrant"
  config.ssh.forward_agent = true

  config.vm.network :public_network
  config.vm.network :private_network, ip: "192.168.69.101"
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 27010, host: 27010

  config.vm.synced_folder "../../../", "/var/kinoulink", type: "nfs"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "KinoulinkPublic"
    vb.memory = 3048
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "bin/provision.sh"
end
