# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "ubuntu/trusty64"

  config.vm.box_check_update = false

  config.vm.network :private_network, ip: "192.168.69.100"
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 27010, host: 27010
  config.ssh.forward_agent = true

  config.vm.synced_folder "../../../", "/var/bizlunch", type: "nfs"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "BizlunchPublic"
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "bootstrap.sh"
end
