#!/usr/bin/env bash

alias sf="setuser www-data php bin/console --env=prod"

cd /opt/tmp

git clone https://github.com/kinoulink/backoffice.git

cd backoffice

composer install

mv . /var/www/

rm -rf /opt/tmp/*
