#!/usr/bin/env bash

mkdir /opt/ktv/tmp

cd /opt/ktv/tmp

git clone https://github.com/kinoulink/backoffice.git

cd backoffice

composer install

mv . /var/www/

rm -rf /opt/ktv/tmp

chown www-data:www-data -R /var/www