version: "2"

services:

  proxy:
    build: proxy
    image: kinoulink/proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: ktv_manager_proxy
    environment:
        - HTTP_AUTH_PASSWORD=$KTV_MANAGER_PASSWORD

  rancher:
    image: rancher/server:v1.1.3
    volumes:
      - rancher_mysql:/var/lib/mysql
      - rancher_cattle:/var/lib/cattle
    labels:
      ktv.infra.proxy.domain: 'rancher'
      ktv.infra.proxy.port: '8080'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ktv_phpmyadmin
    hostname: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=node-1.docker.ktv.internal
    labels:
        ktv.infra.proxy.domain: 'phpmyadmin'

  rsync:
    image: kinoulink/sync
    build: rsync
    privileged: true
    restart: always
    ports:
      - 873:873

  backoffice:
    image: kinoulink/backoffice
    build: backoffice
    container_name: ktv_backoffice
    hostname: backoffice
    environment:
      - APP_VERSION=master
    volumes:
      - composer_cache:/opt/ktv/composer/cache
      - backoffice_www:/opt/ktv/volume
    labels:
        ktv.infra.proxy.domain: 'backoffice'

volumes:

  composer_cache:
      driver: local

  backoffice_www:
      driver: local

  rancher_mysql:
      driver: local

  rancher_cattle:
      driver: local
