version: 2

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    mem_limit: 268435456
    container_name: ktv_phpmyadmin
    hostname: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql

  rsync:
    image: nabeken/docker-volume-container-rsync
    mem_limit: 268435456
    privileged: true
    restart: always
    working_dir: /docker
    volumes:
      - /opt/ktv/shares:/docker
    ports:
      - 873:873