version: "2"

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    mem_limit: 268435456
    container_name: ktv_phpmyadmin
    hostname: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=node-1.docker.ktv.internal

  rsync:
    image: kinoulink/sync
    mem_limit: 268435456
    privileged: true
    restart: always
    ports:
      - 873:873

  backoffice:
    image: kinoulink/backoffice
    container_name: ktv_backoffice
    hostname: backoffice
    mem_limit: 268435456
    ports:
      - 80:80
    environment:
      - APP_VERSION=master
    volumes:
      - composer_cache:/opt/ktv/composer/cache
      - backoffice_www:/opt/ktv/volume

volumes:

  composer_cache:
      driver: local

  backoffice_www:
      driver: local