version: "2"

services:

  proxy:
    build: proxy
    image: kinoulink/proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
        - HTTP_AUTH_PASSWORD=admin
    restart: always

  vpn:
    image: kylemanna/openvpn
    volumes:
      - vpn_config:/etc/openvpn
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    extra_hosts:
      - "vpn.admin.affichage.cloud:127.0.0.1"
    restart: always

  rancher:
    image: rancher/server:v1.1.3
    volumes:
      - rancher_mysql:/var/lib/mysql
      - rancher_cattle:/var/lib/cattle
    restart: always
    labels:
      ktv.infra.proxy.domain: 'rancher'
      ktv.infra.proxy.port: '8080'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=node-1.docker.ktv.internal
    restart: always
    labels:
        ktv.infra.proxy.domain: 'phpmyadmin'

  rsync:
    image: kinoulink/sync
    build: rsync
    privileged: true
    restart: always
    ports:
      - 873:873

#  backoffice:
#    image: kinoulink/backoffice
#    build: backoffice
#    container_name: ktv_backoffice
#    hostname: backoffice
#    environment:
#      - APP_VERSION=master
#    volumes:
#      - composer_cache:/opt/ktv/composer/cache
#      - backoffice_www:/opt/ktv/volume
#    labels:
#        ktv.infra.proxy.domain: 'backoffice'

volumes:

  composer_cache:
      driver: local

  backoffice_www:
      driver: local

  rancher_mysql:
      driver: local

  rancher_cattle:
      driver: local

  vpn_config:
      driver: local
